### ISSUE TITLE
Cannot get BASH_ARGV into a nested function

### ISSUE THREAD

**Issue by pilak** [UmkaDK/getopts_long#12]
Hi,

I'm using getopts_long inside a nested function contained in the script I launch but when executing getopts_long, it seems to not retrieve the #BASH_ARGV since ${#BASH_ARGV} equals 0

Do you have any easy solution to solve this ?

**Comment by pilak** [comment]
Hi,

I'm using getopts_long inside a nested function contained in the script I launch but when executing getopts_long, it seems to not retrieve the #BASH_ARGV since ${#} equals 0 

Do you have any easy solution to solve this ?

**Comment by UrsaDK** [comment]
Hi @pilak, 

[Using even the default `getops` inside a function](https://stackoverflow.com/questions/16654607/using-getopts-inside-a-bash-function) is not exactly straight forward... But I'll see if I can add some test coverage for this use-case and workout what's going on with BASH_ARGV.

One thing that would really help is a simple example of how you're using `getopts_long`, as I'm not entirely sure what you mean by "nested function". Are you talking about a function within a function? Also, are you attempting to process arguments supplied to the script or to the function?

**Comment by dodecatheon** [comment]
@UrsaDK :  It is possible to use `builtin getopts` inside a function:
```
foo () {
  OPTIND=1
  while getopts ':ab:' OPT ; do
    case "$OPT" in
      a) a_stuff ;;
      b) b_stuff=$OPTARG ;;
      ...
```
However, with `getopts_long`, you can't do a similar loop, because, in the way you currently use OPTIND, you are looking through the arguments of the overall script, not the arguments of the function.

If you want to use `getopts_long` in a subcommand, for example passing the shifted arguments to `foo` using `foo "$@"`, this is problematic.

**Comment by dodecatheon** [comment]
Answering my own question, you already handle this.

```
foo () {
  OPTIND=1
  while getopts_long ':ab: alpha bravo:' OPT "$@"; do
    case "$OPT" in
      a|alpha) a_stuff=1 ;;
      b|bravo) b_stuff=$OPTARG ;;
      ...
```

**Comment by UrsaDK** [comment]
Thanks for following this up with an answer @dodecatheon! 😄

I think, since this question came up twice now, I should probably add it to the README, and maybe even include it as a separate scenario in the tests. I'll add it to me TODO list! 

For now, I'm going to resolve this as "Works as expected" since there isn't a difference between the way the original `geopts` and my `getopts_long` behave in this use case.
